services:
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  
  db:
    image: postgres:16-alpine
    environment: 
      POSTGRES_DB: "lab2-db"
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./bd/migrations:/docker-entrypoint-initdb.d
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lab2-db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    secrets: 
      - db_user
      - db_password
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgadmin:
  postgres:

secrets:
  db_password:
    file: bd/secrets/db-password.txt
  db_user:
    file: bd/secrets/db-user.txt
