services:
  web:
    build: .
    container_name: dpo_4_php
    ports:
      - "8080:80"
    env_file:
      - ./.env
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  db:
    image: postgres:16-alpine
    container_name: dpo_4_db
    env_file:
      - ./.env
    user: postgres
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s
    restart: unless-stopped
  
  pgadmin:
    container_name: dpo_4_pgadmin
    image: dpage/pgadmin4:7.2
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8081:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgadmin:
  postgres:

